/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Circulo;
import Clases.Rectangulo;
import java.awt.Color;

/**
 *
 * @author AA729
 */
public class FormularioFiguras extends javax.swing.JFrame {
    
    //Atributos
    private Rectangulo oRec;
    private Circulo oCirc;

    /**
     * Creates new form FormularioFiguras
     */
    public FormularioFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioRectangulo = new javax.swing.JRadioButton();
        jRadioCirculo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextTamaño = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jButtonDer = new javax.swing.JButton();
        jButtonIzq = new javax.swing.JButton();
        jButtonArriba = new javax.swing.JButton();
        jButtonAbajo = new javax.swing.JButton();
        panel1 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioRectangulo.setFont(new java.awt.Font("Meiryo", 1, 18)); // NOI18N
        jRadioRectangulo.setText("RECTÁNGULO");
        jRadioRectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioRectanguloMouseClicked(evt);
            }
        });
        jRadioRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRectanguloActionPerformed(evt);
            }
        });

        jRadioCirculo.setFont(new java.awt.Font("Meiryo", 1, 18)); // NOI18N
        jRadioCirculo.setText("CÍRCULO");
        jRadioCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioCirculoMouseClicked(evt);
            }
        });
        jRadioCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCirculoActionPerformed(evt);
            }
        });

        jLabel1.setText("COORDENADA X:");

        jLabel2.setText("COORDENADA Y:");

        jLabel3.setText("TAMAÑO:");

        jButtonCrear.setText("CREAR");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonDer.setText("DERECHA");
        jButtonDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDerActionPerformed(evt);
            }
        });

        jButtonIzq.setText("IZQUIERDA");
        jButtonIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzqActionPerformed(evt);
            }
        });

        jButtonArriba.setText("ARRIBA");
        jButtonArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArribaActionPerformed(evt);
            }
        });

        jButtonAbajo.setText("ABAJO");
        jButtonAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCrear)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIzq)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonArriba)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAbajo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextX, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextY, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioRectangulo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioRectangulo)
                    .addComponent(jRadioCirculo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrear)
                    .addComponent(jButtonDer)
                    .addComponent(jButtonIzq)
                    .addComponent(jButtonArriba)
                    .addComponent(jButtonAbajo))
                .addGap(42, 42, 42)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRectanguloActionPerformed
        if(this.jRadioRectangulo.isSelected())
            this.jRadioCirculo.setSelected(false);
    }//GEN-LAST:event_jRadioRectanguloActionPerformed

    private void jRadioRectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioRectanguloMouseClicked
        if(this.jRadioRectangulo.isSelected())
            this.jRadioCirculo.setSelected(false);
    }//GEN-LAST:event_jRadioRectanguloMouseClicked

    private void jRadioCirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioCirculoMouseClicked
        if(this.jRadioCirculo.isSelected())
            this.jRadioRectangulo.setSelected(false);
    }//GEN-LAST:event_jRadioCirculoMouseClicked

    private void jRadioCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCirculoActionPerformed
        if(this.jRadioCirculo.isSelected())
            this.jRadioRectangulo.setSelected(false);
    }//GEN-LAST:event_jRadioCirculoActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        int x = Integer.parseInt(this.jTextX.getText());
        int y = Integer.parseInt(this.jTextY.getText());
        int tamaño = Integer.parseInt(this.jTextTamaño.getText());
        
        if(this.jRadioRectangulo.isSelected()){
            //Crear el objeto rectángulo
            oRec = new Rectangulo(x, y, tamaño);
            oRec.mostrar(this.panel1.getGraphics(), Color.BLACK);
        }
        else{
            //Crear el objeto Circulo
            oCirc = new Circulo(x,y,tamaño);
            oCirc.mostrar(this.panel1.getGraphics(), Color.BLACK);
            
        }
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDerActionPerformed
        if(this.jRadioRectangulo.isSelected()){
            oRec.moverDerecha();
            oRec.mostrar(this.panel1.getGraphics(), Color.RED);
        }
        else{
            oCirc.moverDerecha();
            oCirc.mostrar(this.panel1.getGraphics(), Color.RED);
        }
            
    }//GEN-LAST:event_jButtonDerActionPerformed

    private void jButtonIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzqActionPerformed
        if(this.jRadioRectangulo.isSelected()){
            oRec.moverIzquierda();
            oRec.mostrar(this.panel1.getGraphics(), Color.RED);
        }
        else{
            oCirc.moverIzquierda();
            oCirc.mostrar(this.panel1.getGraphics(), Color.RED);
        }
    }//GEN-LAST:event_jButtonIzqActionPerformed

    private void jButtonArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArribaActionPerformed
        if(this.jRadioRectangulo.isSelected()){
            oRec.moverArriba();
            oRec.mostrar(this.panel1.getGraphics(), Color.RED);
        }
        else{
            oCirc.moverArriba();
            oCirc.mostrar(this.panel1.getGraphics(), Color.RED);
        }
    }//GEN-LAST:event_jButtonArribaActionPerformed

    private void jButtonAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbajoActionPerformed
        if(this.jRadioRectangulo.isSelected()){
            oRec.moverAbajo();
            oRec.mostrar(this.panel1.getGraphics(), Color.RED);
        }
        else{
            oCirc.moverAbajo();
            oCirc.mostrar(this.panel1.getGraphics(), Color.RED);
        }
    }//GEN-LAST:event_jButtonAbajoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioFiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbajo;
    private javax.swing.JButton jButtonArriba;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonDer;
    private javax.swing.JButton jButtonIzq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioCirculo;
    private javax.swing.JRadioButton jRadioRectangulo;
    private javax.swing.JTextField jTextTamaño;
    private javax.swing.JTextField jTextX;
    private javax.swing.JTextField jTextY;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
