/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Persona;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author AA729
 */
public class Formulario1 extends javax.swing.JFrame {
    
    //Declarar tres objetos del tipo Persona
    private Persona oPer1, oPer2, oPer3;
    
    //Variables para recibir los valores de los jTextFields
    String nombre;
    int edad;
    double estatura;
    char sexo;
    int dia;
    int mes;
    int año;

    /**
     * Creates new form Formulario1
     */
    public Formulario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextEstatura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboSexo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextDia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextMes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextAño = new javax.swing.JTextField();
        jButtonP1 = new javax.swing.JButton();
        jButtonP2 = new javax.swing.JButton();
        jButtonP3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMostrar = new javax.swing.JTable();
        jLabelMayorEdad = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("EDAD:");

        jLabel3.setText("ESTATURA:");

        jLabel4.setText("SEXO:");

        jComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "H", "M" }));

        jLabel5.setText("DIA:");

        jLabel6.setText("MES:");

        jLabel7.setText("AÑO:");

        jTextAño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAñoFocusLost(evt);
            }
        });

        jButtonP1.setText("PERSONA 1");
        jButtonP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP1ActionPerformed(evt);
            }
        });

        jButtonP2.setText("PERSONA 2");
        jButtonP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP2ActionPerformed(evt);
            }
        });

        jButtonP3.setText("PERSONA 3");
        jButtonP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP3ActionPerformed(evt);
            }
        });

        jTableMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "EDAD", "ESTATURA", "SEXO", "DIA", "MES", "AÑO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMostrar);

        jLabelMayorEdad.setBackground(new java.awt.Color(255, 51, 51));
        jLabelMayorEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMayorEdad.setOpaque(true);

        jButtonLimpiar.setText("LIMPIAR");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextNombre)
                    .addComponent(jTextEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jTextEstatura, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAño, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jTextMes, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jTextDia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelMayorEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonP1)
                .addGap(18, 18, 18)
                .addComponent(jButtonP2)
                .addGap(18, 18, 18)
                .addComponent(jButtonP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP1)
                    .addComponent(jButtonP2)
                    .addComponent(jButtonP3)
                    .addComponent(jButtonLimpiar))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMayorEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP1ActionPerformed
        nombre= this.jTextNombre.getText();
        edad= Integer.parseInt(this.jTextEdad.getText());
        estatura= Double.parseDouble(this.jTextEstatura.getText());
        sexo= this.jComboSexo.getSelectedItem().toString().charAt(0);
        dia= Integer.parseInt(this.jTextDia.getText());
        mes= Integer.parseInt(this.jTextMes.getText());
        año= Integer.parseInt(this.jTextAño.getText());
        
        //Crear el oPer1
        oPer1 = new Persona(nombre, edad, estatura, sexo, dia, mes, año);
        
        //Validar la fecha de nacimiento
        if(oPer1.verificarFecha())
        {
            oPer1.mostrarDatos(jTableMostrar);
            if(oPer1.esMayorDeEdad())
                this.jLabelMayorEdad.setText("ES MAYOR DE EDAD");
            else
                this.jLabelMayorEdad.setText("NO ES MAYOR DE EDAD");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "La fecha de nacimiento es incorrecta, vuelve a escribirla");
            this.jTextDia.setText("");
            this.jTextMes.setText("");
            this.jTextAño.setText("");
        }
        
        
    }//GEN-LAST:event_jButtonP1ActionPerformed

    private void jButtonP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP2ActionPerformed
        nombre= this.jTextNombre.getText();
        estatura= Double.parseDouble(this.jTextEstatura.getText());
        sexo= this.jComboSexo.getSelectedItem().toString().charAt(0);
        dia= Integer.parseInt(this.jTextDia.getText());
        mes= Integer.parseInt(this.jTextMes.getText());
        año= Integer.parseInt(this.jTextAño.getText());
        
        //Crear el oPer2
        oPer2.setNombre(nombre);
        oPer2.setEdad(edad);
        oPer2.setEstatura(estatura);
        oPer2.setSexo(sexo);
        oPer2.setDia(dia);
        oPer2.setMes(mes);
        oPer2.setAño(año);
        
        //Validar la fecha de nacimiento
        if(oPer2.verificarFecha())
        {
            oPer2.mostrarDatos(jTableMostrar);
            if(oPer2.esMayorDeEdad())
                this.jLabelMayorEdad.setText("ES MAYOR DE EDAD");
            else
                this.jLabelMayorEdad.setText("NO ES MAYOR DE EDAD");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "La fecha de nacimiento es incorrecta, vuelve a escribirla");
            this.jTextDia.setText("");
            this.jTextMes.setText("");
            this.jTextAño.setText("");
        }
    }//GEN-LAST:event_jButtonP2ActionPerformed

    private void jButtonP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP3ActionPerformed
        nombre= this.jTextNombre.getText();
        estatura= Double.parseDouble(this.jTextEstatura.getText());
        sexo= this.jComboSexo.getSelectedItem().toString().charAt(0);
        dia= Integer.parseInt(this.jTextDia.getText());
        mes= Integer.parseInt(this.jTextMes.getText());
        
        //Crear el oPer3
        oPer3 = new Persona(nombre, estatura, sexo, dia, mes);
        
        //Validar la fecha de nacimiento
        if(oPer3.verificarFecha())
        {
            oPer3.mostrarDatos(jTableMostrar);
            if(oPer3.esMayorDeEdad())
                this.jLabelMayorEdad.setText("ES MAYOR DE EDAD");
            else
                this.jLabelMayorEdad.setText("NO ES MAYOR DE EDAD");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "La fecha de nacimiento es incorrecta, vuelve a escribirla");
            this.jTextDia.setText("");
            this.jTextMes.setText("");
            this.jTextAño.setText("");
        }
    }//GEN-LAST:event_jButtonP3ActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        //Limpiar los objetos del Formulario
        this.jTextNombre.setText("");
        this.jTextEdad.setText("");
        this.jTextEstatura.setText("");
        this.jComboSexo.setSelectedIndex(0);
        this.jTextDia.setText("");
        this.jTextMes.setText("");
        this.jTextAño.setText("");
        this.jTableMostrar.setValueAt("", 0, 0);
        this.jTableMostrar.setValueAt("", 0, 1);
        this.jTableMostrar.setValueAt("", 0, 2);
        this.jTableMostrar.setValueAt("", 0, 3);
        this.jTableMostrar.setValueAt("", 0, 4);
        this.jTableMostrar.setValueAt("", 0, 5);
        this.jTableMostrar.setValueAt("", 0, 6);
        this.jLabelMayorEdad.setText("");
        
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextAñoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAñoFocusLost
        Calendar añoActual = Calendar.getInstance();
        int año = Integer.parseInt(this.jTextAño.getText());
        int edad = Integer.parseInt(this.jTextEdad.getText());
        if(añoActual.get(Calendar.YEAR) != (año+edad))
            JOptionPane.showMessageDialog(rootPane, "El año de nacimiento es incorrecto");
    }//GEN-LAST:event_jTextAñoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonP1;
    private javax.swing.JButton jButtonP2;
    private javax.swing.JButton jButtonP3;
    private javax.swing.JComboBox<String> jComboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelMayorEdad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMostrar;
    private javax.swing.JTextField jTextAño;
    private javax.swing.JTextField jTextDia;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextEstatura;
    private javax.swing.JTextField jTextMes;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
