/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Carro;
import javax.swing.JOptionPane;

/**
 *
 * @author AA729
 */
public class Formulario1 extends javax.swing.JFrame {
     //Declarar objeto del tipo Carro
    Carro c1=null, c2=null, c3=null;
    
    
    //Declarar las variables en la que se recibiran los datos
    int idCarro;
    String matricula;
    int año;
    String marca;
    double precio;

    /**
     * Creates new form Formulario1
     */
    public Formulario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTFPrecio = new javax.swing.JTextField();
        jButCrearC1 = new javax.swing.JButton();
        jButCrearC2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaC1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaC2 = new javax.swing.JTextArea();
        jButCrearC3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFIdCarro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFAño = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaC3 = new javax.swing.JTextArea();
        jTFMarca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("PRECIO:");

        jButCrearC1.setText("CREAR C1");
        jButCrearC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCrearC1ActionPerformed(evt);
            }
        });

        jButCrearC2.setText("CREAR C2");
        jButCrearC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCrearC2ActionPerformed(evt);
            }
        });

        jTextAreaC1.setEditable(false);
        jTextAreaC1.setColumns(20);
        jTextAreaC1.setRows(5);
        jScrollPane1.setViewportView(jTextAreaC1);

        jTextAreaC2.setEditable(false);
        jTextAreaC2.setColumns(20);
        jTextAreaC2.setRows(5);
        jScrollPane2.setViewportView(jTextAreaC2);

        jButCrearC3.setText("C3 COPIA DE C1");
        jButCrearC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCrearC3ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID CARRO:");

        jLabel2.setText("MATRÍCULA:");

        jLabel3.setText("AÑO:");

        jLabel4.setText("MARCA:");

        jTextAreaC3.setEditable(false);
        jTextAreaC3.setColumns(20);
        jTextAreaC3.setRows(5);
        jScrollPane3.setViewportView(jTextAreaC3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButCrearC1)
                                .addGap(55, 55, 55)
                                .addComponent(jButCrearC2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jButCrearC3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFIdCarro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFAño, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTFAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButCrearC1)
                            .addComponent(jButCrearC2)
                            .addComponent(jButCrearC3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCrearC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCrearC1ActionPerformed
        idCarro= Integer.parseInt(this.jTFIdCarro.getText());
        matricula= this.jTFMatricula.getText();
        año= Integer.parseInt(this.jTFAño.getText());
        marca= this.jTFMarca.getText();
        precio= Double.parseDouble(this.jTFPrecio.getText());

        //Crear el objeto con el constructor default
        c1= new Carro();

        //Asignar los datos con el método set
        c1.setIdCarro(idCarro);
        c1.setMatricula(matricula);
        c1.setAño(año);
        c1.setMarca(marca);
        c1.setPrecio(precio);

        //Mandar llamar al método toString()
        this.jTextAreaC1.setText(c1.toString());

    }//GEN-LAST:event_jButCrearC1ActionPerformed

    private void jButCrearC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCrearC2ActionPerformed
        idCarro= Integer.parseInt(this.jTFIdCarro.getText());
        matricula= this.jTFMatricula.getText();
        año= Integer.parseInt(this.jTFAño.getText());
        marca= this.jTFMarca.getText();
        precio= Double.parseDouble(this.jTFPrecio.getText());

        //Crear el objeto c2 con el constructor que recibe todos los datos como parametro
        c2= new Carro(idCarro,matricula,año,marca,precio);

        //Mostrar el objeto c2 con el método toString()
        this.jTextAreaC2.setText(c2.toString());
    }//GEN-LAST:event_jButCrearC2ActionPerformed

    private void jButCrearC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCrearC3ActionPerformed
        if(c1 != null){
            c3 = new Carro(c1);
            this.jTextAreaC3.setText(c3.toString());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "El objeto c1 no ha sido creado");
        }
    }//GEN-LAST:event_jButCrearC3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCrearC1;
    private javax.swing.JButton jButCrearC2;
    private javax.swing.JButton jButCrearC3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFAño;
    private javax.swing.JTextField jTFIdCarro;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFMatricula;
    private javax.swing.JTextField jTFPrecio;
    private javax.swing.JTextArea jTextAreaC1;
    private javax.swing.JTextArea jTextAreaC2;
    private javax.swing.JTextArea jTextAreaC3;
    // End of variables declaration//GEN-END:variables
}
