/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.CalculosEmpleados;
import javax.swing.JOptionPane;

/**
 *
 * @author AA726
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEjecutar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelO1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelO2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelO3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelSueldo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelSueldo2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelSueldo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEjecutar.setText("EJECUTAR");
        jButtonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjecutarActionPerformed(evt);
            }
        });

        jLabel1.setText("OBJETO 1:");

        jLabelO1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelO1.setOpaque(true);

        jLabel3.setText("OBJETO 2:");

        jLabelO2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelO2.setOpaque(true);

        jLabel5.setText("OBJETO 3:");

        jLabelO3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelO3.setOpaque(true);

        jLabel2.setText("SUELDO MENSUAL:");

        jLabelSueldo1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSueldo1.setOpaque(true);

        jLabel4.setText("SUELDO MENSUAL:");

        jLabelSueldo2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSueldo2.setOpaque(true);

        jLabel6.setText("SUELDO MENSUAL:");

        jLabelSueldo3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSueldo3.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelSueldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelSueldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelSueldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabelO3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelO2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonEjecutar)
                    .addComponent(jLabelO1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonEjecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelO1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelSueldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelO2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelSueldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelO3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelSueldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjecutarActionPerformed
        
        //BOTÓN EJECUTAR
        //CREAR 3 OBJETOS DEL TIPO CalculosEmpleados
        CalculosEmpleados oCE1 = new CalculosEmpleados("Juan", "Gerente", 23450, "Administración", 17);
        CalculosEmpleados oCE2 = new CalculosEmpleados("Marcelo", "Secretario", 15600, "Dirección", 22);
        CalculosEmpleados oCE3 = new CalculosEmpleados("Eduardo", "Asistente Gral.", 12400, "Finanzas", 37);
        
        //Mostrar todos sus atributos
        this.jLabelO1.setText("Nombre:"+oCE1.getNombre()+" / Puesto: "+oCE1.getPuesto()+" / Sueldo: "+oCE1.getSueldo()+" / Depto: "+oCE1.getNombreDepartamento()+" / Num de empleados: "+oCE1.getNumeroEmpleados());
        this.jLabelO2.setText("Nombre:"+oCE2.getNombre()+" / Puesto: "+oCE2.getPuesto()+" / Sueldo: "+oCE2.getSueldo()+" / Depto: "+oCE2.getNombreDepartamento()+" / Num de empleados: "+oCE2.getNumeroEmpleados());
        this.jLabelO3.setText("Nombre:"+oCE3.getNombre()+" / Puesto: "+oCE3.getPuesto()+" / Sueldo: "+oCE3.getSueldo()+" / Depto: "+oCE3.getNombreDepartamento()+" / Num de empleados: "+oCE3.getNumeroEmpleados());
        
        //Mostrar el sueldo que obtuvo en el mes
        this.jLabelSueldo1.setText(oCE1.calcularSueldo(2)+"");
        this.jLabelSueldo2.setText(oCE1.calcularSueldo(23)+"");
        this.jLabelSueldo3.setText(oCE1.calcularSueldo(0)+"");
        
        //Determinar cual de los objetos tiene mayor sueldo
//        double mayor = 0.0;
//        for(int i=1; i>3 ; i++){
//            if(oCE1.getSueldo() > mayor)
//                mayor = oCE1.getSueldo();
//        }

        //Solucion
        double mayor = 0.0;
        if(oCE1.getSueldo() > mayor){
            mayor = oCE1.getSueldo();
            if(oCE2.getSueldo() > mayor){
                mayor = oCE2.getSueldo();
                if(oCE3.getSueldo() > mayor){
                    mayor = oCE3.getSueldo();
                }
            }
            else{
                if(oCE3.getSueldo() > mayor){
                  mayor = oCE3.getSueldo();  
                }
            }
        }
        
        JOptionPane.showMessageDialog(null, "El sueldo mayor es " + mayor);
        
        
    }//GEN-LAST:event_jButtonEjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelO1;
    private javax.swing.JLabel jLabelO2;
    private javax.swing.JLabel jLabelO3;
    private javax.swing.JLabel jLabelSueldo1;
    private javax.swing.JLabel jLabelSueldo2;
    private javax.swing.JLabel jLabelSueldo3;
    // End of variables declaration//GEN-END:variables
}
