/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Carro;
import Clases.Estacionamiento;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfredo Puentes Vargas
 */
public class Formulario extends javax.swing.JFrame {
    
    Estacionamiento oEst;
    Carro oC1 = null, oC2 = null, oC3 = null, oC4 = null, oC5 = null;
    
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        
        //Crear el objeto oEst
        oEst = new Estacionamiento(5);
        this.jLabelDisponibles.setText(oEst.getLugares() + "");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextNumeroHoras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelDisponibles = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerNoLugar = new javax.swing.JSpinner();
        jButtonEstacionar = new javax.swing.JButton();
        jButtonCobro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MATRÍCULA:");

        jLabel2.setText("NO. HORAS:");

        jLabel3.setText("LUGARES DISPONIBLES:");

        jLabelDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDisponibles.setOpaque(true);

        jLabel4.setText("NO. LUGAR:");

        jSpinnerNoLugar.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jButtonEstacionar.setText("ESTACIONAR");
        jButtonEstacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstacionarActionPerformed(evt);
            }
        });

        jButtonCobro.setText("COBRO");
        jButtonCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCobroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEstacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(49, 49, 49))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(54, 54, 54)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNumeroHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jTextMatricula)
                            .addComponent(jSpinnerNoLugar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerNoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextNumeroHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEstacionar)
                    .addComponent(jButtonCobro))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEstacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstacionarActionPerformed
        
        String matricula = this.jTextMatricula.getText();
        
        if(matricula.equals(""))
            JOptionPane.showMessageDialog(rootPane, "Escribe la matrícula del carro");
        
        else{
        switch(this.jSpinnerNoLugar.getValue().toString()){
            case "1":
                if(oC1 == null){
                    oC1 = new Carro(matricula);
                    oC1.estacionarVehiculo(oEst);
                    JOptionPane.showMessageDialog(null, "Carro 1 estacionado");
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                }
                else
                    JOptionPane.showMessageDialog(null, "El espacio está ocupado");
                break;
            case "2":
                if(oC2 == null){
                    oC2 = new Carro(matricula);
                    oC2.estacionarVehiculo(oEst);
                    JOptionPane.showMessageDialog(null, "Carro 2 estacionado");
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                }
                else
                    JOptionPane.showMessageDialog(null, "El espacio está ocupado");
                break;
            case "3":
                if(oC3 == null){
                    oC3 = new Carro(matricula);
                    oC3.estacionarVehiculo(oEst);
                    JOptionPane.showMessageDialog(null, "Carro 3 estacionado");
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                }
                else
                    JOptionPane.showMessageDialog(null, "El espacio está ocupado");
                break;
            case "4":
                if(oC4 == null){
                    oC4 = new Carro(matricula);
                    oC4.estacionarVehiculo(oEst);
                    JOptionPane.showMessageDialog(null, "Carro 4 estacionado");
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                }
                else
                    JOptionPane.showMessageDialog(null, "El espacio está ocupado");
                break;
            case "5":
                if(oC5 == null){
                    oC5 = new Carro(matricula);
                    oC5.estacionarVehiculo(oEst);
                    JOptionPane.showMessageDialog(null, "Carro 5 estacionado");
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                }
                else
                    JOptionPane.showMessageDialog(null, "El espacio está ocupado");
                break;
        }
        }
    }//GEN-LAST:event_jButtonEstacionarActionPerformed

    private void jButtonCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCobroActionPerformed
    try{
        int horas = Integer.parseInt(this.jTextNumeroHoras.getText());
        
        if (horas > 24)
            horas = 24;
        
        switch(this.jSpinnerNoLugar.getValue().toString()){
            case "1":
                if(oC1 != null){
                    JOptionPane.showMessageDialog(rootPane, "Cobro: " + oC1.factura(horas));
                    oEst.incrementarLugares();
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                    oC1 = null;
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "El lugar 1 no está ocupado");
                break;
            case "2":
                if(oC2 != null){
                    JOptionPane.showMessageDialog(rootPane, "Cobro: " + oC2.factura(horas));
                    oEst.incrementarLugares();
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                    oC2 = null;
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "El lugar 2 no está ocupado");
                break;
            case "3":
                if(oC3 != null){
                    JOptionPane.showMessageDialog(rootPane, "Cobro: " + oC3.factura(horas));
                    oEst.incrementarLugares();
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                    oC3 = null;
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "El lugar 3 no está ocupado");
                break;
            case "4":
                if(oC4 != null){
                    JOptionPane.showMessageDialog(rootPane, "Cobro: " + oC4.factura(horas));
                    oEst.incrementarLugares();
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                    oC4 = null;
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "El lugar 4 no está ocupado");
                break;
            case "5":
                if(oC5 != null){
                    JOptionPane.showMessageDialog(rootPane, "Cobro: " + oC5.factura(horas));
                    oEst.incrementarLugares();
                    this.jLabelDisponibles.setText(oEst.getLugares()+"");
                    oC5 = null;
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "El lugar 5 no está ocupado");
                break;
        }
    }
    catch(NumberFormatException o){
        JOptionPane.showMessageDialog(rootPane, "Escribe el dato correcto " + o.getMessage());
    }
    }//GEN-LAST:event_jButtonCobroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCobro;
    private javax.swing.JButton jButtonEstacionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDisponibles;
    private javax.swing.JSpinner jSpinnerNoLugar;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextNumeroHoras;
    // End of variables declaration//GEN-END:variables
}
