/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Empleado;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AA731
 */
public class Fomulario extends javax.swing.JFrame {

    Empleado oEmp;
    ArrayList <Empleado> oAL;
    JFileChooser jfch;
    File archivo;
    
    /**
     * Creates new form Fomulario
     */
    
    public Fomulario() {
        initComponents();
        oAL = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextNoEmpleado1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextNoEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextSueldo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextPuesto = new javax.swing.JTextField();
        jButtonAlta = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jButtonCambios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextNoEmpleadoBaja = new javax.swing.JTextField();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("No. Empleado:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("No. Empleado:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Sueldo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Puesto:");

        jButtonAlta.setText("ALTA");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonBaja.setText("BAJA");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        jButtonCambios.setText("CAMBIOS");
        jButtonCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO. EMPLEADO", "NOMBRE", "SUELDO", "PUESTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonGuardar.setText("GUARDAR Y SALIR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("No. Empleado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNoEmpleadoBaja))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextPuesto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextSueldo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextNoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAlta)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonCambios)
                        .addGap(15, 15, 15)
                        .addComponent(jButtonGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextNoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNoEmpleadoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jButtonBaja)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Métodos para manipular el ArrayList
    public void altaEmpAL(Empleado oEmp){
        oAL.add(oEmp);
    }   
    
    public int buscarEmpAL(int numEmpleado){
        for(int i=0; i<oAL.size(); i++){
            if(oAL.get(i).getNumEmpleado() == numEmpleado)
                return i;
        }
        return -1;
    }
    
    public void modificarEmpAL(int pos, Empleado oEmp){
        oAL.set(pos, oEmp);
    }
    public void eliminarEmpAL(int pos){
        oAL.remove(pos);
    }
    
    public void mostrarEmpALTable(JTable tabla){
        DefaultTableModel modelo = (DefaultTableModel)tabla.getModel();
        modelo.setRowCount(oAL.size());
        
        for(int i=0; i<oAL.size(); i++){
            tabla.setValueAt(oAL.get(i).getNumEmpleado(), i, 0);
            tabla.setValueAt(oAL.get(i).getNombEmpleado(), i, 1);
            tabla.setValueAt(oAL.get(i).getSueldoEmpleado(), i, 2);
            tabla.setValueAt(oAL.get(i).getPuestoEmpleado(), i, 3);
        }
        
    }
    
    //Métodos para manipular el archivo de texto
    public void escribirArchivoTexto(){
        FileWriter oFW = null;
        PrintWriter oPW = null;
        
        try {
            oFW = new FileWriter("G:\\ARCHIVOS\\Programación Orientada a Objetos\\Archivos POO\\P5T6.txt", false);
            oPW = new PrintWriter(oFW);
            
            //Ciclo para leer los datos del ArrayList y guardarlos en el archivo de texto
            for(int i=0; i<oAL.size(); i++){
                oPW.print(oAL.get(i).getNumEmpleado() + "-");
                oPW.print(oAL.get(i).getNombEmpleado() + "-");
                oPW.print(oAL.get(i).getSueldoEmpleado() + "-");
                oPW.println(oAL.get(i).getPuestoEmpleado());
            }
            
            oFW.close();
            oPW.close();
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error de escritura");
        }
    }    
        
    public void leerArchivoTexto(){
        FileReader oFR = null;
        BufferedReader oBR = null;
            
        try {
            oFR = new FileReader("G:\\ARCHIVOS\\Programación Orientada a Objetos\\Archivos POO\\P5T6.txt");
            oBR = new BufferedReader(oFR);

            String cad = oBR.readLine();
            Empleado oEmp;

            while(cad != null){
                StringTokenizer oST = new StringTokenizer(cad, "-");
                oEmp = new Empleado(Integer.parseInt(oST.nextToken()), oST.nextToken(), Double.parseDouble(oST.nextToken()), oST.nextToken());
                //Guardar el objeto emplpeado en el ArrayList
                this.altaEmpAL(oEmp);
                //leer la siguiente linea del archivo
                cad = oBR.readLine();
            }

            oFR.close();
            oBR.close();

        }catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error de lectura");
        }catch(IOException ex){
            JOptionPane.showMessageDialog(rootPane, "Error de lectura");
        }
            
    }
    
    public void guardarArchivoTexto(){
        
        PrintWriter oPW;
        
        try{
            oPW = new PrintWriter(new BufferedWriter(new FileWriter(archivo + ".txt")));
            
            //Ciclo para leer los datos del ArrayList y guardarlos en el archivo de texto
            for(int i=0; i<oAL.size(); i++){
                oPW.print(oAL.get(i).getNumEmpleado()+"-");
                oPW.print(oAL.get(i).getNombEmpleado()+"-");
                oPW.print(oAL.get(i).getSueldoEmpleado()+"-");
                oPW.println(oAL.get(i).getPuestoEmpleado());
            }
            
            oPW.close();
            
        }catch(IOException ex){
            JOptionPane.showMessageDialog(null, "Error de escritura");
        }
    }
    
    
    private void jButtonCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiosActionPerformed
        
        int noEmp = Integer.parseInt(this.jTextNoEmpleadoBaja.getText());
        
        //Buscar la pos en el ArrayList
        int pos = this.buscarEmpAL(noEmp);
        
        if(pos != -1){
            oEmp = new Empleado(Integer.parseInt(this.jTextNoEmpleado.getText()), this.jTextNombre.getText(), Double.parseDouble(this.jTextSueldo.getText()), this.jTextPuesto.getText());
            //Modificar el objeto Empleado en el ArrayList
            this.modificarEmpAL(pos, oEmp);
            //Guardar el ArrayList en el archivo
            this.escribirArchivoTexto();
            //Mostrar el ArrayList en la tabla
            this.mostrarEmpALTable(jTable1);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "El empleado no existe");
        
    }//GEN-LAST:event_jButtonCambiosActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        
        oEmp = new Empleado(Integer.parseInt(this.jTextNoEmpleado.getText()), this.jTextNombre.getText(), Double.parseDouble(this.jTextSueldo.getText()), this.jTextPuesto.getText());
        //Guardar el objeto Empleado en el ArrayList
        this.altaEmpAL(oEmp);
        //Guardar el ArrayList en el archivo
        this.escribirArchivoTexto();
        //Mostrar el ArrayList en la tabla
        this.mostrarEmpALTable(jTable1);
        
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        //Leer el archivo de texto
        this.leerArchivoTexto();
        //Mostrar el ArrayList
        this.mostrarEmpALTable(jTable1);
        
    }//GEN-LAST:event_formWindowOpened

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        
        int noEmp = Integer.parseInt(this.jTextNoEmpleadoBaja.getText());
        
        //Buscar la pos en el ArrayList
        int pos = this.buscarEmpAL(noEmp);
        
        if(pos != -1){
            int res = JOptionPane.showConfirmDialog(rootPane, "Seguro que quieres eliminar al empleado?");
            if(res == 0){
                //Dar de baja al empleado en el ArrayList
                this.eliminarEmpAL(pos);
                //Escribir en el archivo de texto
                this.escribirArchivoTexto();
                //Mostrar el ArrayList en la tabla
                this.mostrarEmpALTable(jTable1);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "El empleado no existe");
        
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        
        jfch = new JFileChooser();
        
        if(jfch.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            archivo = jfch.getSelectedFile();
            this.guardarArchivoTexto();
        }
        this.dispose();
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fomulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fomulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fomulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fomulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fomulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonCambios;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextNoEmpleado;
    private javax.swing.JTextField jTextNoEmpleado1;
    private javax.swing.JTextField jTextNoEmpleadoBaja;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPuesto;
    private javax.swing.JTextField jTextSueldo;
    // End of variables declaration//GEN-END:variables
}

