/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.CuentaAhorro;
import Clases.CuentaCorriente;
import Clases.CuentaCorrienteConInt;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author AA730
 */
public class Cuentas extends javax.swing.JFrame {

    String nombre;
    String cuenta;
    double saldo;
    double tipoDeInteres;
    
    CuentaAhorro oCA;
    CuentaCorriente oCC;
    CuentaCorrienteConInt oCCI;
    
    DecimalFormat df;
    
    /**
     * Creates new form Cuentas
     */
    public Cuentas() {
        initComponents();
        df = new DecimalFormat("$#.##");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextNumeroCuenta = new javax.swing.JTextField();
        jTextSaldo = new javax.swing.JTextField();
        jTextTipoInteres = new javax.swing.JTextField();
        jPanelCA = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextCuotaMantenimiento = new javax.swing.JTextField();
        jButtonCrearAhorro = new javax.swing.JButton();
        jButtonCAIntereses = new javax.swing.JButton();
        jButtonCAComisiones = new javax.swing.JButton();
        jLabelCAIntereses = new javax.swing.JLabel();
        jLabelCAComisiones = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelCASaldo = new javax.swing.JLabel();
        jPanelCC = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextNoTransacciones = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextImportePorTrans = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextNoExcentas = new javax.swing.JTextField();
        jButtonCrearCorriente = new javax.swing.JButton();
        jLabelCCIntereses = new javax.swing.JLabel();
        jLabelCCComisiones = new javax.swing.JLabel();
        jLabelCCSaldo = new javax.swing.JLabel();
        jButtonCCIntereses = new javax.swing.JButton();
        jButtonCCComisiones = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanelCCI = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextNoTransaccionesCI = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextImportePorTransCI = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextNoExcentasCI = new javax.swing.JTextField();
        jButtonCrearCorrienteIntereses = new javax.swing.JButton();
        jLabelCCIIntereses = new javax.swing.JLabel();
        jButtonCCIIntereses = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabelCCISaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DATOS DE LA CUENTA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NÚMERO DE CUENTA:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("SALDO:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("TIPO DE INTERÉS:");

        jPanelCA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CUENTA AHORRO");

        jLabel9.setText("CUOTA DE MANTENIMIENTO:");

        jButtonCrearAhorro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCrearAhorro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCrearAhorro.setForeground(new java.awt.Color(255, 0, 0));
        jButtonCrearAhorro.setText("CREAR");
        jButtonCrearAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearAhorroActionPerformed(evt);
            }
        });

        jButtonCAIntereses.setText("INTERESES");
        jButtonCAIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCAInteresesActionPerformed(evt);
            }
        });

        jButtonCAComisiones.setText("COMISIONES");
        jButtonCAComisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCAComisionesActionPerformed(evt);
            }
        });

        jLabelCAIntereses.setBackground(new java.awt.Color(51, 102, 255));
        jLabelCAIntereses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCAIntereses.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCAIntereses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCAIntereses.setOpaque(true);

        jLabelCAComisiones.setBackground(new java.awt.Color(255, 0, 0));
        jLabelCAComisiones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCAComisiones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCAComisiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCAComisiones.setOpaque(true);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SALDO :");

        jLabelCASaldo.setBackground(new java.awt.Color(0, 176, 13));
        jLabelCASaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCASaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCASaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCASaldo.setOpaque(true);

        javax.swing.GroupLayout jPanelCALayout = new javax.swing.GroupLayout(jPanelCA);
        jPanelCA.setLayout(jPanelCALayout);
        jPanelCALayout.setHorizontalGroup(
            jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCALayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(jTextCuotaMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanelCALayout.createSequentialGroup()
                        .addGroup(jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCrearAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelCALayout.createSequentialGroup()
                                .addGroup(jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonCAComisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonCAIntereses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCASaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCAIntereses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCAComisiones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCALayout.setVerticalGroup(
            jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCALayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextCuotaMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCrearAhorro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCAIntereses)
                    .addComponent(jLabelCAIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCAComisiones)
                    .addComponent(jLabelCAComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCASaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanelCC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CUENTA CORRIENTE");

        jLabel11.setText("NO. TRANSACCIONES:");

        jLabel12.setText("IMPORTE POR TRANS:");

        jLabel13.setText("NO. TRANS. EXCENTAS:");

        jButtonCrearCorriente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCrearCorriente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCrearCorriente.setForeground(new java.awt.Color(255, 0, 0));
        jButtonCrearCorriente.setText("CREAR");
        jButtonCrearCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCorrienteActionPerformed(evt);
            }
        });

        jLabelCCIntereses.setBackground(new java.awt.Color(51, 102, 255));
        jLabelCCIntereses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCCIntereses.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCCIntereses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCCIntereses.setOpaque(true);

        jLabelCCComisiones.setBackground(new java.awt.Color(255, 0, 0));
        jLabelCCComisiones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCCComisiones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCCComisiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCCComisiones.setOpaque(true);

        jLabelCCSaldo.setBackground(new java.awt.Color(0, 176, 13));
        jLabelCCSaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCCSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCCSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCCSaldo.setOpaque(true);

        jButtonCCIntereses.setText("INTERESES");
        jButtonCCIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCCInteresesActionPerformed(evt);
            }
        });

        jButtonCCComisiones.setText("COMISIONES");
        jButtonCCComisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCCComisionesActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SALDO:");

        javax.swing.GroupLayout jPanelCCLayout = new javax.swing.GroupLayout(jPanelCC);
        jPanelCC.setLayout(jPanelCCLayout);
        jPanelCCLayout.setHorizontalGroup(
            jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCCLayout.createSequentialGroup()
                        .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCCIntereses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCCComisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCCLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCCIntereses, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jLabelCCComisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCCLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCCSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonCrearCorriente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCCLayout.createSequentialGroup()
                        .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNoTransacciones)
                            .addComponent(jTextNoExcentas)
                            .addComponent(jTextImportePorTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCCLayout.setVerticalGroup(
            jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCCLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextNoTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextImportePorTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextNoExcentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCrearCorriente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCCIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCCIntereses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCCComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCCComisiones, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCCSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanelCCI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CUENTA CORRIENTE CON INTERESES");

        jLabel15.setText("NO. TRANSACCIONES:");

        jLabel16.setText("IMPORTE POR TRANS:");

        jLabel17.setText("NO. TRANS. EXCENTAS:");

        jButtonCrearCorrienteIntereses.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCrearCorrienteIntereses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCrearCorrienteIntereses.setForeground(new java.awt.Color(255, 0, 0));
        jButtonCrearCorrienteIntereses.setText("CREAR");
        jButtonCrearCorrienteIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCorrienteInteresesActionPerformed(evt);
            }
        });

        jLabelCCIIntereses.setBackground(new java.awt.Color(51, 102, 255));
        jLabelCCIIntereses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCCIIntereses.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCCIIntereses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCCIIntereses.setOpaque(true);

        jButtonCCIIntereses.setText("INTERESES");
        jButtonCCIIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCCIInteresesActionPerformed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("SALDO:");

        jLabelCCISaldo.setBackground(new java.awt.Color(0, 176, 13));
        jLabelCCISaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCCISaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCCISaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCCISaldo.setOpaque(true);

        javax.swing.GroupLayout jPanelCCILayout = new javax.swing.GroupLayout(jPanelCCI);
        jPanelCCI.setLayout(jPanelCCILayout);
        jPanelCCILayout.setHorizontalGroup(
            jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCCILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCCILayout.createSequentialGroup()
                        .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCCILayout.createSequentialGroup()
                                .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCCIIntereses, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                                .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCCILayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabelCCIIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCCILayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelCCISaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonCrearCorrienteIntereses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCCILayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelCCILayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(27, 27, 27)
                            .addComponent(jTextNoTransaccionesCI, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGroup(jPanelCCILayout.createSequentialGroup()
                            .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17))
                            .addGap(19, 19, 19)
                            .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextNoExcentasCI, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(jTextImportePorTransCI, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                    .addContainerGap()))
        );
        jPanelCCILayout.setVerticalGroup(
            jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCCILayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(112, 112, 112)
                .addComponent(jButtonCrearCorrienteIntereses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCCIIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCCIIntereses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCCISaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCCILayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jTextNoTransaccionesCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jTextImportePorTransCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelCCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jTextNoExcentasCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jTextNumeroCuenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextTipoInteres)
                            .addComponent(jTextSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextTipoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearAhorroActionPerformed
        
        try{
            nombre = this.jTextNombre.getText();
            cuenta = this.jTextNumeroCuenta.getText();
            saldo = Double.parseDouble(this.jTextSaldo.getText());
            tipoDeInteres = Double.parseDouble(this.jTextTipoInteres.getText());

            double cuotaMtto = Double.parseDouble(this.jTextCuotaMantenimiento.getText());

            oCA = new CuentaAhorro(cuotaMtto, nombre, cuenta, saldo, tipoDeInteres);
            JOptionPane.showMessageDialog(rootPane, "La CUENTA AHORRO ha sido creada exitosamente");
        }
        
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Escribe los datos correctamente");
        }
        
    }//GEN-LAST:event_jButtonCrearAhorroActionPerformed

    private void jButtonCAInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCAInteresesActionPerformed
        
        try{
            double intereses = oCA.intereses();
            this.jLabelCAIntereses.setText(df.format(intereses));

            this.jLabelCASaldo.setText("$" + df.format(oCA.getSaldo()));
        }
        
        catch(NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane, "La cuenta ahorro no ha sido abierta");
        }
        
    }//GEN-LAST:event_jButtonCAInteresesActionPerformed

    private void jButtonCAComisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCAComisionesActionPerformed
        
        try{
            double comisiones = oCA.comisiones();
            this.jLabelCAComisiones.setText(df.format(comisiones));

            this.jLabelCASaldo.setText("$" + df.format(oCA.getSaldo()));
        }
        
        catch(NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane, "La cuenta ahorro no ha sido abierta");
        }
        
    }//GEN-LAST:event_jButtonCAComisionesActionPerformed

    private void jButtonCrearCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCorrienteActionPerformed
        
        try{
            nombre = this.jTextNombre.getText();
            cuenta = this.jTextNumeroCuenta.getText();
            saldo = Double.parseDouble(this.jTextSaldo.getText());
            tipoDeInteres = Double.parseDouble(this.jTextTipoInteres.getText());

            int transacciones = Integer.parseInt(this.jTextNoTransacciones.getText());
            double importePorTrans = Double.parseDouble(this.jTextImportePorTrans.getText());
            int transExentas = Integer.parseInt(this.jTextNoExcentas.getText());

            oCC = new CuentaCorriente(transacciones, importePorTrans, transExentas, nombre, cuenta, saldo, tipoDeInteres);        
            JOptionPane.showMessageDialog(rootPane, "La CUENTA CORRIENTE ha sido creada exitosamente");
        }
        
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Escribe los datos correctamente");
        }
        
    }//GEN-LAST:event_jButtonCrearCorrienteActionPerformed

    private void jButtonCrearCorrienteInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCorrienteInteresesActionPerformed
        
        try{
            nombre = this.jTextNombre.getText();
            cuenta = this.jTextNumeroCuenta.getText();
            saldo = Double.parseDouble(this.jTextSaldo.getText());
            tipoDeInteres = Double.parseDouble(this.jTextTipoInteres.getText());

            int transacciones = Integer.parseInt(this.jTextNoTransaccionesCI.getText());
            double importePorTrans = Double.parseDouble(this.jTextImportePorTransCI.getText());
            int transExentas = Integer.parseInt(this.jTextNoExcentasCI.getText());

            oCCI = new CuentaCorrienteConInt(transacciones, importePorTrans, transExentas, nombre, cuenta, saldo, tipoDeInteres);        
            JOptionPane.showMessageDialog(rootPane, "La CUENTA CORRIENTE CON INTERESES ha sido creada exitosamente");
        }
        
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Escribe los datos correctamente");
        }
        
    }//GEN-LAST:event_jButtonCrearCorrienteInteresesActionPerformed

    private void jButtonCCInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCCInteresesActionPerformed

        try{
            double intereses = oCC.intereses();
            this.jLabelCCIntereses.setText(df.format(intereses));

            this.jLabelCCSaldo.setText("$" + df.format(oCC.getSaldo()));
        }
        
        catch(NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane, "La cuenta corriente no ha sido abierta");
        }
        
    }//GEN-LAST:event_jButtonCCInteresesActionPerformed

    private void jButtonCCComisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCCComisionesActionPerformed
        
        try{
            double comisiones = oCC.comisiones();
            this.jLabelCCComisiones.setText(df.format(comisiones));

            this.jLabelCCSaldo.setText("$" + df.format(oCC.getSaldo()));
        }
        
        catch(NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane, "La cuenta corriente no ha sido abierta");
        }
        
    }//GEN-LAST:event_jButtonCCComisionesActionPerformed

    private void jButtonCCIInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCCIInteresesActionPerformed
        
        try{
            double intereses = oCCI.intereses();
            this.jLabelCCIIntereses.setText(df.format(intereses));

            this.jLabelCCISaldo.setText("$" + df.format(oCCI.getSaldo()));
        }
        
        catch(NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane, "La cuenta corriente con intereses no ha sido abierta");
        }
    }//GEN-LAST:event_jButtonCCIInteresesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCAComisiones;
    private javax.swing.JButton jButtonCAIntereses;
    private javax.swing.JButton jButtonCCComisiones;
    private javax.swing.JButton jButtonCCIIntereses;
    private javax.swing.JButton jButtonCCIntereses;
    private javax.swing.JButton jButtonCrearAhorro;
    private javax.swing.JButton jButtonCrearCorriente;
    private javax.swing.JButton jButtonCrearCorrienteIntereses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCAComisiones;
    private javax.swing.JLabel jLabelCAIntereses;
    private javax.swing.JLabel jLabelCASaldo;
    private javax.swing.JLabel jLabelCCComisiones;
    private javax.swing.JLabel jLabelCCIIntereses;
    private javax.swing.JLabel jLabelCCISaldo;
    private javax.swing.JLabel jLabelCCIntereses;
    private javax.swing.JLabel jLabelCCSaldo;
    private javax.swing.JPanel jPanelCA;
    private javax.swing.JPanel jPanelCC;
    private javax.swing.JPanel jPanelCCI;
    private javax.swing.JTextField jTextCuotaMantenimiento;
    private javax.swing.JTextField jTextImportePorTrans;
    private javax.swing.JTextField jTextImportePorTransCI;
    private javax.swing.JTextField jTextNoExcentas;
    private javax.swing.JTextField jTextNoExcentasCI;
    private javax.swing.JTextField jTextNoTransacciones;
    private javax.swing.JTextField jTextNoTransaccionesCI;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumeroCuenta;
    private javax.swing.JTextField jTextSaldo;
    private javax.swing.JTextField jTextTipoInteres;
    // End of variables declaration//GEN-END:variables
}
