/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Empleado;
import Clases.Empresa;
import Clases.Fecha;
import Clases.Gerente;
import Clases.Ubicacion;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AA729
 */
public class FormularioAltas extends javax.swing.JFrame {
    //Atributos
    public ArrayList <Empleado> arrL1=null, arrL2=null, arrL3=null;
    public Empresa oEmp1=null, oEmp2=null, oEmp3=null;
    
    /**
     * Creates new form FormularioAltas
     */
    public FormularioAltas() {
        initComponents();
        //Crear los ArrayList
        arrL1 = new ArrayList();
        arrL2 = new ArrayList();
        arrL3 = new ArrayList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jTextNomEmpresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGerenteGeneral = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUbicacion = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEmpleado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButtonAleatorio = new javax.swing.JButton();
        jButtonAlta = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jButtonCrearEmpresa = new javax.swing.JButton();
        jRadioEmpresa1 = new javax.swing.JRadioButton();
        jRadioEmpresa2 = new javax.swing.JRadioButton();
        jRadioEmpresa3 = new javax.swing.JRadioButton();
        jButtonAleatorioEmpleado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonAConsultas = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("NOMBRE DE L A EMPRESA:");

        jTextNomEmpresa.setBackground(new java.awt.Color(51, 102, 255));
        jTextNomEmpresa.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("GERENTE GENERAL:");

        jTableGerenteGeneral.setBackground(new java.awt.Color(51, 102, 255));
        jTableGerenteGeneral.setForeground(new java.awt.Color(255, 255, 255));
        jTableGerenteGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "SUELDO", "DIA", "MES", "AÑO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGerenteGeneral.setGridColor(new java.awt.Color(255, 255, 255));
        jTableGerenteGeneral.setRowHeight(21);
        jTableGerenteGeneral.setShowHorizontalLines(true);
        jTableGerenteGeneral.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTableGerenteGeneral);
        if (jTableGerenteGeneral.getColumnModel().getColumnCount() > 0) {
            jTableGerenteGeneral.getColumnModel().getColumn(0).setMinWidth(160);
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("UBICACION:");

        jTableUbicacion.setBackground(new java.awt.Color(51, 102, 255));
        jTableUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        jTableUbicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "CALLE", "NÚMERO", "COLONIA", "CP", "CIUDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUbicacion.setGridColor(new java.awt.Color(255, 255, 255));
        jTableUbicacion.setRowHeight(21);
        jTableUbicacion.setShowHorizontalLines(true);
        jTableUbicacion.setShowVerticalLines(true);
        jScrollPane2.setViewportView(jTableUbicacion);
        if (jTableUbicacion.getColumnModel().getColumnCount() > 0) {
            jTableUbicacion.getColumnModel().getColumn(0).setMinWidth(160);
        }

        jTableEmpleado.setBackground(new java.awt.Color(51, 102, 255));
        jTableEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "PUESTO", "DIA", "MES", "AÑO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpleado.setGridColor(new java.awt.Color(255, 255, 255));
        jTableEmpleado.setRowHeight(21);
        jTableEmpleado.setShowHorizontalLines(true);
        jTableEmpleado.setShowVerticalLines(true);
        jScrollPane3.setViewportView(jTableEmpleado);
        if (jTableEmpleado.getColumnModel().getColumnCount() > 0) {
            jTableEmpleado.getColumnModel().getColumn(0).setMinWidth(160);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("EMPLEADOS:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("ARRAY DE EMPLEADOS:");

        jTableEmpleados.setBackground(new java.awt.Color(51, 102, 255));
        jTableEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "PUESTO", "DIA", "MES", "AÑO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpleados.setGridColor(new java.awt.Color(255, 255, 255));
        jTableEmpleados.setShowHorizontalLines(true);
        jTableEmpleados.setShowVerticalLines(true);
        jScrollPane4.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(0).setMinWidth(160);
        }

        jButtonAleatorio.setBackground(new java.awt.Color(0, 0, 51));
        jButtonAleatorio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonAleatorio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAleatorio.setText("ALEATORIO");
        jButtonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatorioActionPerformed(evt);
            }
        });

        jButtonAlta.setBackground(new java.awt.Color(0, 0, 51));
        jButtonAlta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonAlta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlta.setText("+");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonBaja.setBackground(new java.awt.Color(0, 0, 51));
        jButtonBaja.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonBaja.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBaja.setText("-");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        jButtonCrearEmpresa.setBackground(new java.awt.Color(0, 0, 255));
        jButtonCrearEmpresa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonCrearEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrearEmpresa.setText("CREAR EMPRESA");
        jButtonCrearEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearEmpresaActionPerformed(evt);
            }
        });

        jRadioEmpresa1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioEmpresa1.setText("EMPRESA 1");
        jRadioEmpresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEmpresa1ActionPerformed(evt);
            }
        });

        jRadioEmpresa2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioEmpresa2.setText("EMPRESA 2");
        jRadioEmpresa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEmpresa2ActionPerformed(evt);
            }
        });

        jRadioEmpresa3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioEmpresa3.setText("EMPRESA 3");
        jRadioEmpresa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEmpresa3ActionPerformed(evt);
            }
        });

        jButtonAleatorioEmpleado.setBackground(new java.awt.Color(0, 0, 51));
        jButtonAleatorioEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonAleatorioEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAleatorioEmpleado.setText("ALEATORIO");
        jButtonAleatorioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatorioEmpleadoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("DAR DE ALTA UNA EMPRESA");

        jButtonAConsultas.setBackground(new java.awt.Color(0, 0, 255));
        jButtonAConsultas.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonAConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAConsultas.setText("IR A CONSULTAS");
        jButtonAConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAConsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAleatorioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(30, 30, 30)
                            .addComponent(jTextNomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                            .addComponent(jButtonAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCrearEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jRadioEmpresa1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioEmpresa2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioEmpresa3)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAleatorio))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonAlta)
                    .addComponent(jButtonBaja)
                    .addComponent(jButtonAleatorioEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearEmpresa)
                    .addComponent(jRadioEmpresa2)
                    .addComponent(jRadioEmpresa3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAConsultas)
                    .addComponent(jRadioEmpresa1))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tablaAlArrayList(ArrayList <Empleado> arrayL, JTable tabla){
        for(int i=0; i<tabla.getRowCount(); i++){
            Fecha oFN = new Fecha(
                    Integer.parseInt(tabla.getValueAt(i, 2).toString()),
                    Integer.parseInt(tabla.getValueAt(i, 3).toString()),
                    Integer.parseInt(tabla.getValueAt(i, 4).toString()));
            Empleado oEmp = new Empleado(
                    tabla.getValueAt(i, 0).toString(),
                    tabla.getValueAt(i, 1).toString(), oFN);
            
            arrayL.add(oEmp);
        }
    }
    
    private void jButtonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatorioActionPerformed
        String []nombEmps = {"Lala","Peñoles", "Pilgrim's", "John Deere", "Bimbo", "Simsa", "Coca cola"};
        Random rnd = new Random();
        this.jTextNomEmpresa.setText(nombEmps[rnd.nextInt(nombEmps.length)]);
                
        Gerente oGer = new Gerente();
        oGer.aleatorioGerente(jTableGerenteGeneral);
        
        Ubicacion oUbi = new Ubicacion();
        oUbi.aleatorioUbicacion(jTableUbicacion);
        
        //Limpiar la tabla empleados
        DefaultTableModel modelo = (DefaultTableModel)this.jTableEmpleados.getModel();
        modelo.setRowCount(0);
        
    }//GEN-LAST:event_jButtonAleatorioActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)this.jTableEmpleados.getModel();
        
        Object[]arreglo = new Object[5];
        arreglo[0] = this.jTableEmpleado.getValueAt(0, 0);
        arreglo[1] = this.jTableEmpleado.getValueAt(0, 1);
        arreglo[2] = this.jTableEmpleado.getValueAt(0, 2);
        arreglo[3] = this.jTableEmpleado.getValueAt(0, 3);
        arreglo[4] = this.jTableEmpleado.getValueAt(0, 4);
        
        modelo.addRow(arreglo);
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)this.jTableEmpleados.getModel();
        modelo.setRowCount(jTableEmpleados.getRowCount()-1);
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonCrearEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearEmpresaActionPerformed
        if(this.jRadioEmpresa1.isSelected()){
            //Atributos de la empresa
            String nombre = this.jTextNomEmpresa.getText();
            
            //Atributos del Gerente General
            String nombGG = this.jTableGerenteGeneral.getValueAt(0, 0).toString();
            double sueldoGG = Double.parseDouble(this.jTableGerenteGeneral.getValueAt(0, 1).toString());
            int dia = Integer.parseInt(this.jTableGerenteGeneral.getValueAt(0,2).toString());
            int mes = Integer.parseInt(this.jTableGerenteGeneral.getValueAt(0,3).toString());
            int año = Integer.parseInt(this.jTableGerenteGeneral.getValueAt(0,4).toString());
            
            //Crear el objeto Fecha
            Fecha fechaNacGG = new Fecha(dia, mes, año);
            
            //Crear el objeto Gerente
            Gerente gerGral = new Gerente(nombGG, sueldoGG, fechaNacGG);
            
            String calle = this.jTableUbicacion.getValueAt(0, 0).toString();
            String num = this.jTableUbicacion.getValueAt(0, 1).toString();
            String col = this.jTableUbicacion.getValueAt(0, 2).toString();
            String cp = this.jTableUbicacion.getValueAt(0, 3).toString();
            String cd = this.jTableUbicacion.getValueAt(0, 4).toString();
            
            //Crear el objeto Ubicacion
            Ubicacion oUbi = new Ubicacion(calle, num, col, cp, cd);
            
            //Llamar al método para pasar los datos de la JTable al ArrayList
            this.tablaAlArrayList(arrL1, jTableEmpleados);
            
            //Crear el objeto Empresa
            oEmp1 = new Empresa(nombre, gerGral, oUbi, arrL1);
            JOptionPane.showMessageDialog(null, "Empresa 1 creada exitosamente");
        }
        else if(this.jRadioEmpresa2.isSelected()){
            //Atributos de la Empresa
            String nombre = this.jTextNomEmpresa.getText();
            
            //Atributos del Gerente General
            String nombGG = this.jTableGerenteGeneral.getValueAt(0, 0).toString();
            double sueldoGG = Double.parseDouble(this.jTableGerenteGeneral.getValueAt(0, 1).toString());
            int dia = Integer.parseInt(this.jTableGerenteGeneral.getValueAt(0,2).toString());
            int mes = Integer.parseInt(this.jTableGerenteGeneral.getValueAt(0,3).toString());
            int año = Integer.parseInt(this.jTableGerenteGeneral.getValueAt(0,4).toString());
            
            //Crear el objeto Fecha
            Fecha fechaNacGG = new Fecha(dia, mes, año);
            
            //Crear el objeto Gerente
            Gerente gerGral = new Gerente(nombGG, sueldoGG, fechaNacGG);
            
            String calle = this.jTableUbicacion.getValueAt(0, 0).toString();
            String num = this.jTableUbicacion.getValueAt(0, 1).toString();
            String col = this.jTableUbicacion.getValueAt(0, 2).toString();
            String cp = this.jTableUbicacion.getValueAt(0, 3).toString();
            String cd = this.jTableUbicacion.getValueAt(0, 4).toString();
            
            //Crear el objeto Ubicacion
            Ubicacion oUbi = new Ubicacion(calle, num, col, cp, cd);
            
            //Llamar al método para pasar los datos de la JTable al ArrayList
            this.tablaAlArrayList(arrL2, jTableEmpleados);
            
            //Crear el objeto Empresa
            oEmp2 = new Empresa(nombre, gerGral, oUbi, arrL2);
            JOptionPane.showMessageDialog(null, "Empresa 2 creada exitosamente");
        }
        else if(this.jRadioEmpresa3.isSelected()){
            //Atributos de la Empresa
            String nombre = this.jTextNomEmpresa.getText();
            
            //Atributos del Gerente General
            String nombGG = this.jTableGerenteGeneral.getValueAt(0, 0).toString();
            double sueldoGG = Double.parseDouble(this.jTableGerenteGeneral.getValueAt(0, 1).toString());
            int dia = Integer.parseInt(this.jTableGerenteGeneral.getValueAt(0,2).toString());
            int mes = Integer.parseInt(this.jTableGerenteGeneral.getValueAt(0,3).toString());
            int año = Integer.parseInt(this.jTableGerenteGeneral.getValueAt(0,4).toString());
            
            //Crear el objeto Fecha
            Fecha fechaNacGG = new Fecha(dia, mes, año);
            
            //Crear el objeto Gerente
            Gerente gerGral = new Gerente(nombGG, sueldoGG, fechaNacGG);
            
            String calle = this.jTableUbicacion.getValueAt(0, 0).toString();
            String num = this.jTableUbicacion.getValueAt(0, 1).toString();
            String col = this.jTableUbicacion.getValueAt(0, 2).toString();
            String cp = this.jTableUbicacion.getValueAt(0, 3).toString();
            String cd = this.jTableUbicacion.getValueAt(0, 4).toString();
            
            //Crear el objeto Ubicacion
            Ubicacion oUbi = new Ubicacion(calle, num, col, cp, cd);
            
            //Llamar al método para pasar los datos de la JTable al ArrayList
            this.tablaAlArrayList(arrL3, jTableEmpleados);
            
            //Crear el objeto Empresa
            oEmp3 = new Empresa(nombre, gerGral, oUbi, arrL3);
            JOptionPane.showMessageDialog(null, "Empresa 3 creada exitosamente");
        }
        else
            JOptionPane.showMessageDialog(null, "Seleccionar una empresa");
    }//GEN-LAST:event_jButtonCrearEmpresaActionPerformed

    private void jRadioEmpresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEmpresa1ActionPerformed
        this.jRadioEmpresa2.setSelected(false);
        this.jRadioEmpresa3.setSelected(false);
    }//GEN-LAST:event_jRadioEmpresa1ActionPerformed

    private void jRadioEmpresa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEmpresa2ActionPerformed
        this.jRadioEmpresa1.setSelected(false);
        this.jRadioEmpresa3.setSelected(false);
    }//GEN-LAST:event_jRadioEmpresa2ActionPerformed

    private void jRadioEmpresa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEmpresa3ActionPerformed
        this.jRadioEmpresa1.setSelected(false);
        this.jRadioEmpresa2.setSelected(false);
    }//GEN-LAST:event_jRadioEmpresa3ActionPerformed

    private void jButtonAleatorioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatorioEmpleadoActionPerformed
        Empleado oEmp = new Empleado();
        oEmp.aleatorioEmpleado(jTableEmpleado);
    }//GEN-LAST:event_jButtonAleatorioEmpleadoActionPerformed

    private void jButtonAConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAConsultasActionPerformed
        FormularioConsultas fConsulta = new FormularioConsultas(this);
        fConsulta.setVisible(true);
    }//GEN-LAST:event_jButtonAConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioAltas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAConsultas;
    private javax.swing.JButton jButtonAleatorio;
    private javax.swing.JButton jButtonAleatorioEmpleado;
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonCrearEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioEmpresa1;
    private javax.swing.JRadioButton jRadioEmpresa2;
    private javax.swing.JRadioButton jRadioEmpresa3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableEmpleado;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTable jTableGerenteGeneral;
    private javax.swing.JTable jTableUbicacion;
    private javax.swing.JTextField jTextNomEmpresa;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
