/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.EmpresaExtranjera;
import Clases.EmpresaNacional;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Puentes Vargas Alfredo - 22130803
 */
public class Prestamos extends javax.swing.JFrame {

    //DECLARACIÓN DE OBJETOS Y VARIABLES
    EmpresaNacional oEN = new EmpresaNacional();
    EmpresaExtranjera oEE = new EmpresaExtranjera();
    DecimalFormat df = new DecimalFormat("#.##");
    
    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
        
        //CAMBIAR EL COLOR DE FONDO DEL FORMULARIO
        getContentPane().setBackground(Color.BLACK);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextPresupuesto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextCantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSpinnerMeses = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jRadioEuros = new javax.swing.JRadioButton();
        jRadioDolares = new javax.swing.JRadioButton();
        jRadioNacional = new javax.swing.JRadioButton();
        jRadioExtranjera = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jButtonSolicitar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelPrestada = new javax.swing.JLabel();
        jLabelMensual = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jButtonAlta = new javax.swing.JButton();
        jButtonProveedores = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SOLICITAR UN PRÉSTAMO");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PRESUPUESTO DE LA EMPRESA:");

        jTextPresupuesto.setBackground(new java.awt.Color(255, 255, 255));
        jTextPresupuesto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPresupuesto.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CANTIDAD A PRESTAR:");

        jTextCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jTextCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextCantidad.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PLAZO DE PAGO:");

        jSpinnerMeses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSpinnerMeses.setModel(new javax.swing.SpinnerNumberModel(6, 6, 12, 1));
        jSpinnerMeses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinnerMeses.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Meses");

        jRadioEuros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioEuros.setForeground(new java.awt.Color(255, 255, 255));
        jRadioEuros.setText("Euros");
        jRadioEuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEurosActionPerformed(evt);
            }
        });

        jRadioDolares.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioDolares.setForeground(new java.awt.Color(255, 255, 255));
        jRadioDolares.setText("Dólares");
        jRadioDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDolaresActionPerformed(evt);
            }
        });

        jRadioNacional.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioNacional.setForeground(new java.awt.Color(255, 255, 255));
        jRadioNacional.setText("Nacional");
        jRadioNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNacionalActionPerformed(evt);
            }
        });

        jRadioExtranjera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioExtranjera.setForeground(new java.awt.Color(255, 255, 255));
        jRadioExtranjera.setText("Extranjera");
        jRadioExtranjera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioExtranjeraActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TIPO DE EMPRESA:");

        jButtonSolicitar.setBackground(new java.awt.Color(0, 0, 255));
        jButtonSolicitar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSolicitar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSolicitar.setText("SOLICITAR PRÉSTAMO");
        jButtonSolicitar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButtonSolicitar.setOpaque(true);
        jButtonSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CANTIDAD MENSUAL A PAGAR:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CANTIDAD TOTAL A PAGAR:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CANTIDAD A PRESTAR:");

        jLabelPrestada.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPrestada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrestada.setForeground(new java.awt.Color(0, 51, 255));
        jLabelPrestada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrestada.setText("$0.00");
        jLabelPrestada.setOpaque(true);

        jLabelMensual.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMensual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMensual.setForeground(new java.awt.Color(0, 51, 255));
        jLabelMensual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensual.setText("$0.00");
        jLabelMensual.setOpaque(true);

        jLabelTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(0, 51, 255));
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal.setText("$0.00");
        jLabelTotal.setOpaque(true);

        jButtonAlta.setBackground(new java.awt.Color(32, 108, 193));
        jButtonAlta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAlta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlta.setText("DAR DE ALTA");
        jButtonAlta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButtonAlta.setOpaque(true);
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonProveedores.setBackground(new java.awt.Color(32, 108, 193));
        jButtonProveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonProveedores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProveedores.setText("PROVEEDORES");
        jButtonProveedores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButtonProveedores.setOpaque(true);
        jButtonProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProveedoresActionPerformed(evt);
            }
        });

        jButtonSalir.setBackground(new java.awt.Color(119, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButtonSalir.setOpaque(true);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MONEDA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinnerMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)))
                                .addGap(60, 60, 60)
                                .addComponent(jButtonSolicitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextCantidad)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextPresupuesto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioDolares)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioEuros))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioNacional)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioExtranjera))
                                            .addComponent(jLabel16))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPrestada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jRadioNacional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioExtranjera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jRadioDolares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioEuros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabelPrestada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelMensual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelTotal))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitarActionPerformed
        
        //BOTÓN SOLICITAR
        
        //Leer los datos ingresados
        double presupuesto = Double.parseDouble(this.jTextPresupuesto.getText());
        double cantPrestar = Double.parseDouble(this.jTextCantidad.getText());
        int meses = Integer.parseInt(this.jSpinnerMeses.getValue().toString());
        
        //Utilizar el método correspondiente e imprimir los resultados
        if(this.jRadioNacional.isSelected()){
            double mensual = oEN.prestamo(presupuesto, cantPrestar, meses);
            double total = mensual * meses;
            this.jLabelPrestada.setText("$" + cantPrestar + " MXN");
            this.jLabelMensual.setText("$" + df.format(mensual) + " MXN");
            this.jLabelTotal.setText("$" + df.format(total) + " MXN");            
        }
        else{
            if(this.jRadioExtranjera.isSelected()){
                double mensual = oEE.prestamo(presupuesto, cantPrestar, meses);
                double total = mensual * meses;
                if(this.jRadioDolares.isSelected()){
                    this.jLabelPrestada.setText("$" + cantPrestar + " USD");
                    this.jLabelMensual.setText("$" + df.format(mensual) + " USD");
                    this.jLabelTotal.setText("$" + df.format(total) + " USD");
                }
                else{
                    if(this.jRadioEuros.isSelected()){
                        this.jLabelPrestada.setText("$" + cantPrestar + " €");
                        this.jLabelMensual.setText("$" + df.format(mensual) + " €");
                        this.jLabelTotal.setText("$" + df.format(total) + " €");
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Debe seleccionar la moneda en la que se realizará el préstamo");
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Debe seleccionar el tipo de empresa para continuar");
        }
        
    }//GEN-LAST:event_jButtonSolicitarActionPerformed

    private void jButtonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProveedoresActionPerformed

        //BOTÓN PROVEEDORES
        Proveedores oPro = new Proveedores();
        oPro.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonProveedoresActionPerformed

    private void jRadioNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNacionalActionPerformed
        
        this.jRadioExtranjera.setSelected(false);
        if(this.jRadioDolares.isSelected() || this.jRadioEuros.isSelected()){
            JOptionPane.showMessageDialog(null, "Las empresas nacionales sólo pueden solicitar préstamos en Pesos Mexicanos (MXN)");
            this.jRadioDolares.setSelected(false);
            this.jRadioEuros.setSelected(false);
            this.jRadioNacional.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioNacionalActionPerformed

    private void jRadioExtranjeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioExtranjeraActionPerformed
        
        this.jRadioNacional.setSelected(false);
        
    }//GEN-LAST:event_jRadioExtranjeraActionPerformed

    private void jRadioDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDolaresActionPerformed
        
        this.jRadioEuros.setSelected(false);
        if(this.jRadioNacional.isSelected()){
            JOptionPane.showMessageDialog(null, "Las empresas nacionales sólo pueden solicitar préstamos en Pesos Mexicanos (MXN)");
            this.jRadioDolares.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioDolaresActionPerformed

    private void jRadioEurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEurosActionPerformed
        
        this.jRadioDolares.setSelected(false);
        if(this.jRadioNacional.isSelected()){
            JOptionPane.showMessageDialog(null, "Las empresas nacionales sólo pueden solicitar préstamos en Pesos Mexicanos (MXN)");
            this.jRadioEuros.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioEurosActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        //BOTÓN SALIR
        this.dispose();

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed

        //BOTÓN ALTA
        AltaEmpresa oAE = new AltaEmpresa();
        oAE.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonProveedores;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSolicitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMensual;
    private javax.swing.JLabel jLabelPrestada;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JRadioButton jRadioDolares;
    private javax.swing.JRadioButton jRadioEuros;
    private javax.swing.JRadioButton jRadioExtranjera;
    private javax.swing.JRadioButton jRadioNacional;
    private javax.swing.JSpinner jSpinnerMeses;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextPresupuesto;
    // End of variables declaration//GEN-END:variables
}
